implementation correction

diff --git a/docker-compose.yaml b/docker-compose.yaml
--- a/docker-compose.yaml
+++ b/docker-compose.yaml
@@ -24,7 +24,7 @@ services:
       - start-dev
       - --import-realm
     volumes:
-      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
+      - ./keycloak/new-export.json:/opt/keycloak/data/import/realm-export.json
     ports:
       - "8080:8080"
     depends_on:
@@ -82,13 +82,15 @@ services:
 
   olap_db:
     image: clickhouse/clickhouse-server:latest
+    depends_on:
+      - debezium_setup
     ports:
       - "8123:8123"
       - "9431:9000"
     volumes:
       - clickhouse-data:/var/lib/clickhouse
       - ./olap-db:/docker-entrypoint-initdb.d
-      - ./materialized-view-reports.sql:/docker-entrypoint-initdb.d/materialized-view-reports.sql
+      - ./olap-setup/materialized-view-reports.sql:/docker-entrypoint-initdb.d/materialized-view-reports.sql
       - ./olap-db:/var/lib/clickhouse/user_files
       - ./olap-db/users.xml:/etc/clickhouse-server/users.d/users.xml
     healthcheck:
@@ -136,7 +138,7 @@ services:
       "
 
   nginx:
-    image: nginx:alpine
+    image: emcniece/nginx-cache-purge
     ports:
       - "8888:80"
     volumes:
@@ -164,7 +166,7 @@ services:
       - redis
       - keycloak
 
-  report:
+  reports:
     build:
       context: ./backend/report
       dockerfile: Dockerfile
@@ -351,8 +353,38 @@ services:
       CONNECT_PLUGIN_PATH: /kafka/connect
       KEY_CONVERTER_SCHEMAS_ENABLE: "false"
       VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
-#    volumes:
-#      - ./debezium/connectors:/kafka/connect:ro
+
+
+  debezium_setup:
+    image: alpine/curl
+    depends_on:
+      - debezium
+    command: |
+      sh -c "
+      # Ожидание доступности Debezium
+      echo 'Waiting for Debezium to start...'
+      while ! curl -s -f http://debezium:8083/connectors > /dev/null 2>&1; do
+      sleep 5
+      echo 'Still waiting for Debezium...'
+      done
+      
+      echo 'Debezium is up! Registering connector...'
+      
+      for i in 1 2 3 4 5 6 7 8 9 10; do
+      echo \"Registration attempt $i...\"
+      if curl -X POST http://debezium:8083/connectors -H 'Content-Type: application/json' -d @/debezium_tmp/connectors/register-crm-connector.json; then
+      echo 'Success!'
+      exit 0
+      fi
+      echo 'Failed, retrying in 5 seconds...'
+      sleep 5
+      done
+      
+      echo 'Failed after 10 attempts'
+      exit 1
+      "
+    volumes:
+      - ./debezium/:/debezium_tmp/
 
 volumes:
   minio_storage:
